x-app: &app
  build:
    context: .
    dockerfile: ./src/backend/Dockerfile.dev
  restart: unless-stopped
  volumes:
    - ./src/backend:/app/src/backend
    - uv-venv:/app/.venv
  env_file:
    - .env

services:
  cfw-backend:
    <<: *app
    container_name: cfw_dev_backend
    ports:
      - "8000:8000"

  cfw-taskiq-worker:
    <<: *app
    container_name: cfw_dev_worker
    command:
      - uv
      - run
      - taskiq
      - worker
      - src.backend.app.utils.di.di_container:broker
      - src.backend.app.utils.taskiq.tasks
      - --log-level
      - INFO

  cfw-taskiq-scheduler:
    <<: *app
    container_name: cfw_dev_scheduler
    command:
      - uv
      - run
      - taskiq
      - scheduler
      - src.backend.app.utils.di.di_container:scheduler
      - --skip-first-run
      - --log-level
      - INFO

  cfw-redis:
    image: redis:alpine
    container_name: cfw_dev_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --save 60 1000
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru

  cfw-postgres:
    image: postgres:alpine
    container_name: cfw_dev_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  uv-venv:
  redis_data:
  postgres_data:
