x-app: &app
  build:
    context: .
    dockerfile: ./src/backend/Dockerfile.dev
  restart: unless-stopped
  volumes:
    - ./src/backend:/app
    - uv-venv:/app/.venv
  env_file:
    - .env

services:
  backend:
    <<: *app
    container_name: cfw_dev_backend
    ports:
      - "8000:8000"

  worker:
    <<: *app
    container_name: cfw_dev_worker
    command:
      - uv
      - run
      - taskiq
      - worker
      - app.utils.tasks:broker
      - app.utils.tasks
      - --log-level
      - INFO

  scheduler:
    <<: *app
    container_name: cfw_dev_scheduler
    command:
      - uv
      - run
      - taskiq
      - scheduler
      - app.utils.tasks:scheduler
      - --skip-first-run
      - --log-level
      - INFO

  redis:
    image: redis:alpine
    container_name: cfw_dev_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --save 60 1000
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru

volumes:
  uv-venv:
  redis_data:
