name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            backend:
              - 'src/backend/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.3.0
      - run: uv python install
      - name: cache uv
        uses: actions/cache@v5.0.4
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-
      - name: cache pytest
        uses: actions/cache@v5.0.4
        with:
          path: .pytest_cache
          key: pytest-${{ runner.os }}-${{ hashFiles('src/backend/**/*.py') }}
          restore-keys: |
            uv-${{ runner.os }}-
      - run: uv sync --frozen
      - run: cp .env.example .env
      - run: uv run pytest
        env:
          TWILIO_TEST_ACCOUNT_SID: ${{ secrets.TWILIO_TEST_ACCOUNT_SID }}
          TWILIO_TEST_AUTH_TOKEN: ${{ secrets.TWILIO_TEST_AUTH_TOKEN }}
